// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"1920","screenHeight":"1080","changeWindowWidthTo":"800","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"core_displayGroupe","status":true,"description":"","parameters":{}},
{"name":"core_Loader","status":true,"description":"loader class\r\nV.1.0\r\nLicense:© M.I.T\r\nVERY IMPORTANT NOTE: Export from texturePacker with trimmed Name (remove extention.png for use tile normal)\r\n└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘","parameters":{}},
{"name":"core_Camera","status":true,"description":"create player and setup for whole game\r\nV.0.1a\r\nLicense:© M.I.T\r\n└───────────────────────────────────────────────────────────────────────────────────────────────────┘","parameters":{}},
{"name":"core_Mouse","status":true,"description":"MOUSE ENGINE\r\nV.0.1a\r\nLicense:© M.I.T\r\n└───────────────────────────────────────────────────────────────────────────────────────────────────┘\r\nControle tous ce qui est associer a la sourits, interaction avec player et camera engine\r\nInitialise avantr le loader , seulement pendant la sceneBOOT","parameters":{}},
{"name":"core_Players","status":true,"description":"create player and setup for whole game\nV.0.1\nLicense:© M.I.T\n└───────────────────────────────────────────────────────────────────────────────────────────────────┘\ndans les class, . pour les objects, function deep (non Json), _ pour les props array bool,","parameters":{}},
{"name":"_SceneManager","status":true,"description":"","parameters":{}},
{"name":"_Scene_Loader","status":true,"description":"","parameters":{}},
{"name":"_Scene_Boot","status":true,"description":"","parameters":{}},
{"name":"_Scene_IntroVideo","status":true,"description":"","parameters":{}},
{"name":"_Scene_Local","status":true,"description":"","parameters":{}},
{"name":"_Scene_Title","status":true,"description":"","parameters":{}},
{"name":"_Scene_Map","status":true,"description":"Scene_Title\r\nV.1.0\r\nLicense:© M.I.T\r\n\r\n└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘\r\nNOTE AND HELP:","parameters":{}},
{"name":"AnimatedSpriteSheets","status":true,"description":"","parameters":{}},
{"name":"pixiMapEditor","status":true,"description":"EDITOR GUI for create map with object sprine JSON (texture packer, spine)\r\nV.1.0A\r\nLicense:© M.I.T\r\n└────────────────────────────────────────────────────────────────────────────────────────────────────┘","parameters":{}}
];
